#!/bin/bash
# Purpose: Select utility commands

OPTIONS=("Night_Light" "Toggle_Display" "Pomodoro" "Record")

SELECTED=$(for opt in ${OPTIONS[@]}; do
  echo "${opt}"
done | wmenu_wrapper -p "utils" -l ${#OPTIONS[@]})

case ${SELECTED} in
    "Night_Light")
      if pgrep wlsunset; then
        pkill wlsunset
        exit 0
      fi
      wlsunset -g 0.8 & disown
      break ;;
    "Toggle_Display")
      swaymsg 'output "LVDS-1" toggle'
      break ;;
    "Pomodoro")
      if pgrep pomodoro; then
        pomodoro "off"
        exit 0
      fi
      pomodoro
      break ;;
    "Record")
      if pgrep wf-recorder; then
        record "off"
        exit 0
      fi
      record
      break ;;
    *)
      exit 1
esac

exit 0
